export const SEARCH_REPOS_REQUEST = 'SEARCH_REPOS_REQUEST';
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
export const SEARCH_REPOS_FAILURE = 'SEARCH_REPOS_FAILURE';

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

export const FETCH_REPO_REQUEST = 'FETCH_REPO_REQUEST';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS';
export const FETCH_REPO_FAILURE = 'FETCH_REPO_FAILURE';
